# coding: utf-8

"""
    Deep Security Smart Check

    Deep Security Smart Check is a container image scanner from Trend Micro.   # noqa: E501

    OpenAPI spec version: 2018-05-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from SmartCheckAPI.api_client import ApiClient


class ScansApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def scans_get(self, **kwargs):  # noqa: E501
        """scans_get  # noqa: E501

        Retrieve a list of scans. Scans are returned in descending order of creation time, so the latest scan is returned first.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.scans_get(async=True)
        >>> result = thread.get()

        :param async bool
        :param str expand: A comma-separated list of attributes to expand in the results. 
        :param str cursor: An encoded value used to retrieve the next set of results for a query that returns more than `limit` results. 
        :param int limit: The maximum number of records to return. 
        :param str registry: When present, the `registry` query parameter will filter the list of scans to those scans where the `source.registry` contains the provided value. If the `exact` query parameter is also provided (and `true`), the filter will do an exact match on the value. 
        :param str repository: When present, the `repository` query parameter will filter the list of scans to those scans where the `source.repository` contains the provided value. If the `exact` query parameter is also provided (and `true`), the filter will do an exact match on the value. 
        :param str tag: When present, the `tag` query parameter will filter the list of scans to those scans where the `source.tag` contains the provided value. If the `exact` query parameter is also provided (and `true`), the filter will do an exact match on the value. 
        :param bool exact: When present (and true), any filtering done using the `registry`, `repository`, and `tag` query parameters will be done using exact matches. 
        :param str status: When present, the `status` query parameter will filter the list of scans to those scans where the `status` value contains one of the provided values. Valid values in the list are `pending`, `in-progress`, `completed-with-findings`, `completed-no-findings`, `failed`. Invalid values are ignored. 
        :return: InlineResponse2003
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.scans_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.scans_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def scans_get_with_http_info(self, **kwargs):  # noqa: E501
        """scans_get  # noqa: E501

        Retrieve a list of scans. Scans are returned in descending order of creation time, so the latest scan is returned first.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.scans_get_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str expand: A comma-separated list of attributes to expand in the results. 
        :param str cursor: An encoded value used to retrieve the next set of results for a query that returns more than `limit` results. 
        :param int limit: The maximum number of records to return. 
        :param str registry: When present, the `registry` query parameter will filter the list of scans to those scans where the `source.registry` contains the provided value. If the `exact` query parameter is also provided (and `true`), the filter will do an exact match on the value. 
        :param str repository: When present, the `repository` query parameter will filter the list of scans to those scans where the `source.repository` contains the provided value. If the `exact` query parameter is also provided (and `true`), the filter will do an exact match on the value. 
        :param str tag: When present, the `tag` query parameter will filter the list of scans to those scans where the `source.tag` contains the provided value. If the `exact` query parameter is also provided (and `true`), the filter will do an exact match on the value. 
        :param bool exact: When present (and true), any filtering done using the `registry`, `repository`, and `tag` query parameters will be done using exact matches. 
        :param str status: When present, the `status` query parameter will filter the list of scans to those scans where the `status` value contains one of the provided values. Valid values in the list are `pending`, `in-progress`, `completed-with-findings`, `completed-no-findings`, `failed`. Invalid values are ignored. 
        :return: InlineResponse2003
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['expand', 'cursor', 'limit', 'registry', 'repository', 'tag', 'exact', 'status']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method scans_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'expand' in params:
            query_params.append(('expand', params['expand']))  # noqa: E501
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'registry' in params:
            query_params.append(('registry', params['registry']))  # noqa: E501
        if 'repository' in params:
            query_params.append(('repository', params['repository']))  # noqa: E501
        if 'tag' in params:
            query_params.append(('tag', params['tag']))  # noqa: E501
        if 'exact' in params:
            query_params.append(('exact', params['exact']))  # noqa: E501
        if 'status' in params:
            query_params.append(('status', params['status']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['token']  # noqa: E501

        return self.api_client.call_api(
            '/scans', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2003',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def scans_id_get(self, id, **kwargs):  # noqa: E501
        """scans_id_get  # noqa: E501

        Retrieve scan details.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.scans_id_get(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: The scan ID.  (required)
        :param str expand: The properties of each scan that should be expanded in the response. The default (`all`) causes all properties to be expanded. 
        :return: InlineResponse2003Scans
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.scans_id_get_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.scans_id_get_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def scans_id_get_with_http_info(self, id, **kwargs):  # noqa: E501
        """scans_id_get  # noqa: E501

        Retrieve scan details.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.scans_id_get_with_http_info(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: The scan ID.  (required)
        :param str expand: The properties of each scan that should be expanded in the response. The default (`all`) causes all properties to be expanded. 
        :return: InlineResponse2003Scans
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'expand']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method scans_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `scans_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []
        if 'expand' in params:
            query_params.append(('expand', params['expand']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['token']  # noqa: E501

        return self.api_client.call_api(
            '/scans/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2003Scans',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def scans_id_layers_layer_id_malware_get(self, id, layer_id, **kwargs):  # noqa: E501
        """scans_id_layers_layer_id_malware_get  # noqa: E501

        List scan malware findings.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.scans_id_layers_layer_id_malware_get(id, layer_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: The scan ID.  (required)
        :param str layer_id: The layer ID.  (required)
        :param str expand: A comma-separated list of attributes to expand in the results. 
        :param str cursor: An encoded value used to retrieve the next set of results for a query that returns more than `limit` results. 
        :param int limit: The maximum number of records to return. 
        :return: InlineResponse2005
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.scans_id_layers_layer_id_malware_get_with_http_info(id, layer_id, **kwargs)  # noqa: E501
        else:
            (data) = self.scans_id_layers_layer_id_malware_get_with_http_info(id, layer_id, **kwargs)  # noqa: E501
            return data

    def scans_id_layers_layer_id_malware_get_with_http_info(self, id, layer_id, **kwargs):  # noqa: E501
        """scans_id_layers_layer_id_malware_get  # noqa: E501

        List scan malware findings.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.scans_id_layers_layer_id_malware_get_with_http_info(id, layer_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: The scan ID.  (required)
        :param str layer_id: The layer ID.  (required)
        :param str expand: A comma-separated list of attributes to expand in the results. 
        :param str cursor: An encoded value used to retrieve the next set of results for a query that returns more than `limit` results. 
        :param int limit: The maximum number of records to return. 
        :return: InlineResponse2005
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'layer_id', 'expand', 'cursor', 'limit']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method scans_id_layers_layer_id_malware_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `scans_id_layers_layer_id_malware_get`")  # noqa: E501
        # verify the required parameter 'layer_id' is set
        if ('layer_id' not in params or
                params['layer_id'] is None):
            raise ValueError("Missing the required parameter `layer_id` when calling `scans_id_layers_layer_id_malware_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'layer_id' in params:
            path_params['layerID'] = params['layer_id']  # noqa: E501

        query_params = []
        if 'expand' in params:
            query_params.append(('expand', params['expand']))  # noqa: E501
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['token']  # noqa: E501

        return self.api_client.call_api(
            '/scans/{id}/layers/{layerID}/malware', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2005',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def scans_id_layers_layer_id_vulnerabilities_get(self, id, layer_id, **kwargs):  # noqa: E501
        """scans_id_layers_layer_id_vulnerabilities_get  # noqa: E501

        List scan vulnerability findings.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.scans_id_layers_layer_id_vulnerabilities_get(id, layer_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: The scan ID.  (required)
        :param str layer_id: The layer ID.  (required)
        :param str expand: A comma-separated list of attributes to expand in the results. 
        :param str cursor: An encoded value used to retrieve the next set of results for a query that returns more than `limit` results. 
        :param int limit: The maximum number of records to return. 
        :return: InlineResponse2006
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.scans_id_layers_layer_id_vulnerabilities_get_with_http_info(id, layer_id, **kwargs)  # noqa: E501
        else:
            (data) = self.scans_id_layers_layer_id_vulnerabilities_get_with_http_info(id, layer_id, **kwargs)  # noqa: E501
            return data

    def scans_id_layers_layer_id_vulnerabilities_get_with_http_info(self, id, layer_id, **kwargs):  # noqa: E501
        """scans_id_layers_layer_id_vulnerabilities_get  # noqa: E501

        List scan vulnerability findings.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.scans_id_layers_layer_id_vulnerabilities_get_with_http_info(id, layer_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: The scan ID.  (required)
        :param str layer_id: The layer ID.  (required)
        :param str expand: A comma-separated list of attributes to expand in the results. 
        :param str cursor: An encoded value used to retrieve the next set of results for a query that returns more than `limit` results. 
        :param int limit: The maximum number of records to return. 
        :return: InlineResponse2006
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'layer_id', 'expand', 'cursor', 'limit']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method scans_id_layers_layer_id_vulnerabilities_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `scans_id_layers_layer_id_vulnerabilities_get`")  # noqa: E501
        # verify the required parameter 'layer_id' is set
        if ('layer_id' not in params or
                params['layer_id'] is None):
            raise ValueError("Missing the required parameter `layer_id` when calling `scans_id_layers_layer_id_vulnerabilities_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501
        if 'layer_id' in params:
            path_params['layerID'] = params['layer_id']  # noqa: E501

        query_params = []
        if 'expand' in params:
            query_params.append(('expand', params['expand']))  # noqa: E501
        if 'cursor' in params:
            query_params.append(('cursor', params['cursor']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['token']  # noqa: E501

        return self.api_client.call_api(
            '/scans/{id}/layers/{layerID}/vulnerabilities', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2006',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def scans_metrics_get(self, **kwargs):  # noqa: E501
        """scans_metrics_get  # noqa: E501

        Retrieve scan metrics.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.scans_metrics_get(async=True)
        >>> result = thread.get()

        :param async bool
        :return: InlineResponse2004
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.scans_metrics_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.scans_metrics_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def scans_metrics_get_with_http_info(self, **kwargs):  # noqa: E501
        """scans_metrics_get  # noqa: E501

        Retrieve scan metrics.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.scans_metrics_get_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :return: InlineResponse2004
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method scans_metrics_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['token']  # noqa: E501

        return self.api_client.call_api(
            '/scans/metrics', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2004',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def scans_post(self, **kwargs):  # noqa: E501
        """scans_post  # noqa: E501

        Create a new scan.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.scans_post(async=True)
        >>> result = thread.get()

        :param async bool
        :param Request6 request:
        :return: InlineResponse2003Scans
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.scans_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.scans_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def scans_post_with_http_info(self, **kwargs):  # noqa: E501
        """scans_post  # noqa: E501

        Create a new scan.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.scans_post_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param Request6 request:
        :return: InlineResponse2003Scans
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['request']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method scans_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'request' in params:
            body_params = params['request']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['token']  # noqa: E501

        return self.api_client.call_api(
            '/scans', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2003Scans',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
