# coding: utf-8

"""
    Deep Security Smart Check

    Deep Security Smart Check is a container image scanner from Trend Micro.   # noqa: E501

    OpenAPI spec version: 2018-05-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from SmartCheckAPI.models.inline_response2006_findings import InlineResponse2006Findings  # noqa: F401,E501
from SmartCheckAPI.models.inline_response2006_vulnerabilities import InlineResponse2006Vulnerabilities  # noqa: F401,E501


class InlineResponse2006Vulnerabilities1(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'namespace_name': 'str',
        'version': 'str',
        'version_format': 'str',
        'vulnerabilities': 'list[InlineResponse2006Vulnerabilities]',
        'findings': 'InlineResponse2006Findings'
    }

    attribute_map = {
        'name': 'name',
        'namespace_name': 'namespaceName',
        'version': 'version',
        'version_format': 'versionFormat',
        'vulnerabilities': 'vulnerabilities',
        'findings': 'findings'
    }

    def __init__(self, name=None, namespace_name=None, version=None, version_format=None, vulnerabilities=None, findings=None):  # noqa: E501
        """InlineResponse2006Vulnerabilities1 - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._namespace_name = None
        self._version = None
        self._version_format = None
        self._vulnerabilities = None
        self._findings = None
        self.discriminator = None

        self.name = name
        self.namespace_name = namespace_name
        self.version = version
        self.version_format = version_format
        self.vulnerabilities = vulnerabilities
        if findings is not None:
            self.findings = findings

    @property
    def name(self):
        """Gets the name of this InlineResponse2006Vulnerabilities1.  # noqa: E501

        The name of an installed package with known vulnerabilities.   # noqa: E501

        :return: The name of this InlineResponse2006Vulnerabilities1.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse2006Vulnerabilities1.

        The name of an installed package with known vulnerabilities.   # noqa: E501

        :param name: The name of this InlineResponse2006Vulnerabilities1.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def namespace_name(self):
        """Gets the namespace_name of this InlineResponse2006Vulnerabilities1.  # noqa: E501

        The namespace that the package `name` is unique within.   # noqa: E501

        :return: The namespace_name of this InlineResponse2006Vulnerabilities1.  # noqa: E501
        :rtype: str
        """
        return self._namespace_name

    @namespace_name.setter
    def namespace_name(self, namespace_name):
        """Sets the namespace_name of this InlineResponse2006Vulnerabilities1.

        The namespace that the package `name` is unique within.   # noqa: E501

        :param namespace_name: The namespace_name of this InlineResponse2006Vulnerabilities1.  # noqa: E501
        :type: str
        """
        if namespace_name is None:
            raise ValueError("Invalid value for `namespace_name`, must not be `None`")  # noqa: E501

        self._namespace_name = namespace_name

    @property
    def version(self):
        """Gets the version of this InlineResponse2006Vulnerabilities1.  # noqa: E501

        The package version that was detected.   # noqa: E501

        :return: The version of this InlineResponse2006Vulnerabilities1.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this InlineResponse2006Vulnerabilities1.

        The package version that was detected.   # noqa: E501

        :param version: The version of this InlineResponse2006Vulnerabilities1.  # noqa: E501
        :type: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def version_format(self):
        """Gets the version_format of this InlineResponse2006Vulnerabilities1.  # noqa: E501

        The version format.   # noqa: E501

        :return: The version_format of this InlineResponse2006Vulnerabilities1.  # noqa: E501
        :rtype: str
        """
        return self._version_format

    @version_format.setter
    def version_format(self, version_format):
        """Sets the version_format of this InlineResponse2006Vulnerabilities1.

        The version format.   # noqa: E501

        :param version_format: The version_format of this InlineResponse2006Vulnerabilities1.  # noqa: E501
        :type: str
        """
        if version_format is None:
            raise ValueError("Invalid value for `version_format`, must not be `None`")  # noqa: E501

        self._version_format = version_format

    @property
    def vulnerabilities(self):
        """Gets the vulnerabilities of this InlineResponse2006Vulnerabilities1.  # noqa: E501

        A list of the known vulnerabilities in this package.   # noqa: E501

        :return: The vulnerabilities of this InlineResponse2006Vulnerabilities1.  # noqa: E501
        :rtype: list[InlineResponse2006Vulnerabilities]
        """
        return self._vulnerabilities

    @vulnerabilities.setter
    def vulnerabilities(self, vulnerabilities):
        """Sets the vulnerabilities of this InlineResponse2006Vulnerabilities1.

        A list of the known vulnerabilities in this package.   # noqa: E501

        :param vulnerabilities: The vulnerabilities of this InlineResponse2006Vulnerabilities1.  # noqa: E501
        :type: list[InlineResponse2006Vulnerabilities]
        """
        if vulnerabilities is None:
            raise ValueError("Invalid value for `vulnerabilities`, must not be `None`")  # noqa: E501

        self._vulnerabilities = vulnerabilities

    @property
    def findings(self):
        """Gets the findings of this InlineResponse2006Vulnerabilities1.  # noqa: E501


        :return: The findings of this InlineResponse2006Vulnerabilities1.  # noqa: E501
        :rtype: InlineResponse2006Findings
        """
        return self._findings

    @findings.setter
    def findings(self, findings):
        """Sets the findings of this InlineResponse2006Vulnerabilities1.


        :param findings: The findings of this InlineResponse2006Vulnerabilities1.  # noqa: E501
        :type: InlineResponse2006Findings
        """

        self._findings = findings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2006Vulnerabilities1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
