# coding: utf-8

"""
    Deep Security Smart Check

    Deep Security Smart Check is a container image scanner from Trend Micro.   # noqa: E501

    OpenAPI spec version: 2018-05-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse2006Findings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'defcon1': 'int',
        'critical': 'int',
        'high': 'int',
        'medium': 'int',
        'low': 'int',
        'negligible': 'int',
        'unknown': 'int'
    }

    attribute_map = {
        'defcon1': 'defcon1',
        'critical': 'critical',
        'high': 'high',
        'medium': 'medium',
        'low': 'low',
        'negligible': 'negligible',
        'unknown': 'unknown'
    }

    def __init__(self, defcon1=None, critical=None, high=None, medium=None, low=None, negligible=None, unknown=None):  # noqa: E501
        """InlineResponse2006Findings - a model defined in Swagger"""  # noqa: E501

        self._defcon1 = None
        self._critical = None
        self._high = None
        self._medium = None
        self._low = None
        self._negligible = None
        self._unknown = None
        self.discriminator = None

        if defcon1 is not None:
            self.defcon1 = defcon1
        if critical is not None:
            self.critical = critical
        if high is not None:
            self.high = high
        if medium is not None:
            self.medium = medium
        if low is not None:
            self.low = low
        if negligible is not None:
            self.negligible = negligible
        if unknown is not None:
            self.unknown = unknown

    @property
    def defcon1(self):
        """Gets the defcon1 of this InlineResponse2006Findings.  # noqa: E501

        The number of \"Defcon1\" vulnerabilities that were found.   # noqa: E501

        :return: The defcon1 of this InlineResponse2006Findings.  # noqa: E501
        :rtype: int
        """
        return self._defcon1

    @defcon1.setter
    def defcon1(self, defcon1):
        """Sets the defcon1 of this InlineResponse2006Findings.

        The number of \"Defcon1\" vulnerabilities that were found.   # noqa: E501

        :param defcon1: The defcon1 of this InlineResponse2006Findings.  # noqa: E501
        :type: int
        """

        self._defcon1 = defcon1

    @property
    def critical(self):
        """Gets the critical of this InlineResponse2006Findings.  # noqa: E501

        The number of critical vulnerabilities that were found.   # noqa: E501

        :return: The critical of this InlineResponse2006Findings.  # noqa: E501
        :rtype: int
        """
        return self._critical

    @critical.setter
    def critical(self, critical):
        """Sets the critical of this InlineResponse2006Findings.

        The number of critical vulnerabilities that were found.   # noqa: E501

        :param critical: The critical of this InlineResponse2006Findings.  # noqa: E501
        :type: int
        """

        self._critical = critical

    @property
    def high(self):
        """Gets the high of this InlineResponse2006Findings.  # noqa: E501

        The number of high-severity vulnerabilities that were found.   # noqa: E501

        :return: The high of this InlineResponse2006Findings.  # noqa: E501
        :rtype: int
        """
        return self._high

    @high.setter
    def high(self, high):
        """Sets the high of this InlineResponse2006Findings.

        The number of high-severity vulnerabilities that were found.   # noqa: E501

        :param high: The high of this InlineResponse2006Findings.  # noqa: E501
        :type: int
        """

        self._high = high

    @property
    def medium(self):
        """Gets the medium of this InlineResponse2006Findings.  # noqa: E501

        The number of medium-severity vulnerabilities that were found.   # noqa: E501

        :return: The medium of this InlineResponse2006Findings.  # noqa: E501
        :rtype: int
        """
        return self._medium

    @medium.setter
    def medium(self, medium):
        """Sets the medium of this InlineResponse2006Findings.

        The number of medium-severity vulnerabilities that were found.   # noqa: E501

        :param medium: The medium of this InlineResponse2006Findings.  # noqa: E501
        :type: int
        """

        self._medium = medium

    @property
    def low(self):
        """Gets the low of this InlineResponse2006Findings.  # noqa: E501

        The number of low-severity vulnerabilities that were found.   # noqa: E501

        :return: The low of this InlineResponse2006Findings.  # noqa: E501
        :rtype: int
        """
        return self._low

    @low.setter
    def low(self, low):
        """Sets the low of this InlineResponse2006Findings.

        The number of low-severity vulnerabilities that were found.   # noqa: E501

        :param low: The low of this InlineResponse2006Findings.  # noqa: E501
        :type: int
        """

        self._low = low

    @property
    def negligible(self):
        """Gets the negligible of this InlineResponse2006Findings.  # noqa: E501

        The number of negligible vulnerabilities that were found.   # noqa: E501

        :return: The negligible of this InlineResponse2006Findings.  # noqa: E501
        :rtype: int
        """
        return self._negligible

    @negligible.setter
    def negligible(self, negligible):
        """Sets the negligible of this InlineResponse2006Findings.

        The number of negligible vulnerabilities that were found.   # noqa: E501

        :param negligible: The negligible of this InlineResponse2006Findings.  # noqa: E501
        :type: int
        """

        self._negligible = negligible

    @property
    def unknown(self):
        """Gets the unknown of this InlineResponse2006Findings.  # noqa: E501

        The number of vulnerabilities with unknown severity that were found.   # noqa: E501

        :return: The unknown of this InlineResponse2006Findings.  # noqa: E501
        :rtype: int
        """
        return self._unknown

    @unknown.setter
    def unknown(self, unknown):
        """Sets the unknown of this InlineResponse2006Findings.

        The number of vulnerabilities with unknown severity that were found.   # noqa: E501

        :param unknown: The unknown of this InlineResponse2006Findings.  # noqa: E501
        :type: int
        """

        self._unknown = unknown

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2006Findings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
