# coding: utf-8

"""
    Deep Security Smart Check

    Deep Security Smart Check is a container image scanner from Trend Micro.   # noqa: E501

    OpenAPI spec version: 2018-05-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from SmartCheckAPI.models.inline_response2003_details_findings_vulnerabilities_total import InlineResponse2003DetailsFindingsVulnerabilitiesTotal  # noqa: F401,E501
from SmartCheckAPI.models.inline_response2003_details_findings_vulnerabilities_unresolved import InlineResponse2003DetailsFindingsVulnerabilitiesUnresolved  # noqa: F401,E501


class InlineResponse2003DetailsFindingsVulnerabilities(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total': 'InlineResponse2003DetailsFindingsVulnerabilitiesTotal',
        'unresolved': 'InlineResponse2003DetailsFindingsVulnerabilitiesUnresolved'
    }

    attribute_map = {
        'total': 'total',
        'unresolved': 'unresolved'
    }

    def __init__(self, total=None, unresolved=None):  # noqa: E501
        """InlineResponse2003DetailsFindingsVulnerabilities - a model defined in Swagger"""  # noqa: E501

        self._total = None
        self._unresolved = None
        self.discriminator = None

        if total is not None:
            self.total = total
        if unresolved is not None:
            self.unresolved = unresolved

    @property
    def total(self):
        """Gets the total of this InlineResponse2003DetailsFindingsVulnerabilities.  # noqa: E501


        :return: The total of this InlineResponse2003DetailsFindingsVulnerabilities.  # noqa: E501
        :rtype: InlineResponse2003DetailsFindingsVulnerabilitiesTotal
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this InlineResponse2003DetailsFindingsVulnerabilities.


        :param total: The total of this InlineResponse2003DetailsFindingsVulnerabilities.  # noqa: E501
        :type: InlineResponse2003DetailsFindingsVulnerabilitiesTotal
        """

        self._total = total

    @property
    def unresolved(self):
        """Gets the unresolved of this InlineResponse2003DetailsFindingsVulnerabilities.  # noqa: E501


        :return: The unresolved of this InlineResponse2003DetailsFindingsVulnerabilities.  # noqa: E501
        :rtype: InlineResponse2003DetailsFindingsVulnerabilitiesUnresolved
        """
        return self._unresolved

    @unresolved.setter
    def unresolved(self, unresolved):
        """Sets the unresolved of this InlineResponse2003DetailsFindingsVulnerabilities.


        :param unresolved: The unresolved of this InlineResponse2003DetailsFindingsVulnerabilities.  # noqa: E501
        :type: InlineResponse2003DetailsFindingsVulnerabilitiesUnresolved
        """

        self._unresolved = unresolved

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2003DetailsFindingsVulnerabilities):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
