# coding: utf-8

"""
    Deep Security Smart Check

    Deep Security Smart Check is a container image scanner from Trend Micro.   # noqa: E501

    OpenAPI spec version: 2018-05-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RegistriesidscansSource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'repository': 'str',
        'tag': 'str'
    }

    attribute_map = {
        'repository': 'repository',
        'tag': 'tag'
    }

    def __init__(self, repository=None, tag=None):  # noqa: E501
        """RegistriesidscansSource - a model defined in Swagger"""  # noqa: E501

        self._repository = None
        self._tag = None
        self.discriminator = None

        if repository is not None:
            self.repository = repository
        if tag is not None:
            self.tag = tag

    @property
    def repository(self):
        """Gets the repository of this RegistriesidscansSource.  # noqa: E501

        The repository name.   # noqa: E501

        :return: The repository of this RegistriesidscansSource.  # noqa: E501
        :rtype: str
        """
        return self._repository

    @repository.setter
    def repository(self, repository):
        """Sets the repository of this RegistriesidscansSource.

        The repository name.   # noqa: E501

        :param repository: The repository of this RegistriesidscansSource.  # noqa: E501
        :type: str
        """
        if repository is not None and len(repository) > 255:
            raise ValueError("Invalid value for `repository`, length must be less than or equal to `255`")  # noqa: E501

        self._repository = repository

    @property
    def tag(self):
        """Gets the tag of this RegistriesidscansSource.  # noqa: E501

        The tag of the image to scan.   # noqa: E501

        :return: The tag of this RegistriesidscansSource.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this RegistriesidscansSource.

        The tag of the image to scan.   # noqa: E501

        :param tag: The tag of this RegistriesidscansSource.  # noqa: E501
        :type: str
        """
        if tag is not None and len(tag) > 255:
            raise ValueError("Invalid value for `tag`, length must be less than or equal to `255`")  # noqa: E501

        self._tag = tag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegistriesidscansSource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
