# coding: utf-8

"""
    Deep Security Smart Check

    Deep Security Smart Check is a container image scanner from Trend Micro.   # noqa: E501

    OpenAPI spec version: 2018-05-01
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Request3(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'str',
        'password': 'str',
        'password_change_required': 'bool',
        'name': 'str',
        'description': 'str',
        'role': 'str'
    }

    attribute_map = {
        'user_id': 'userID',
        'password': 'password',
        'password_change_required': 'passwordChangeRequired',
        'name': 'name',
        'description': 'description',
        'role': 'role'
    }

    def __init__(self, user_id=None, password=None, password_change_required=None, name=None, description=None, role=None):  # noqa: E501
        """Request3 - a model defined in Swagger"""  # noqa: E501

        self._user_id = None
        self._password = None
        self._password_change_required = None
        self._name = None
        self._description = None
        self._role = None
        self.discriminator = None

        if user_id is not None:
            self.user_id = user_id
        if password is not None:
            self.password = password
        if password_change_required is not None:
            self.password_change_required = password_change_required
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if role is not None:
            self.role = role

    @property
    def user_id(self):
        """Gets the user_id of this Request3.  # noqa: E501

        A unique name for the user.   # noqa: E501

        :return: The user_id of this Request3.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Request3.

        A unique name for the user.   # noqa: E501

        :param user_id: The user_id of this Request3.  # noqa: E501
        :type: str
        """
        if user_id is not None and len(user_id) > 64:
            raise ValueError("Invalid value for `user_id`, length must be less than or equal to `64`")  # noqa: E501

        self._user_id = user_id

    @property
    def password(self):
        """Gets the password of this Request3.  # noqa: E501

        A password for the user.   # noqa: E501

        :return: The password of this Request3.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this Request3.

        A password for the user.   # noqa: E501

        :param password: The password of this Request3.  # noqa: E501
        :type: str
        """
        if password is not None and len(password) > 1024:
            raise ValueError("Invalid value for `password`, length must be less than or equal to `1024`")  # noqa: E501

        self._password = password

    @property
    def password_change_required(self):
        """Gets the password_change_required of this Request3.  # noqa: E501

        If `true`, the user will not be able to perform any actions until they change their password.   # noqa: E501

        :return: The password_change_required of this Request3.  # noqa: E501
        :rtype: bool
        """
        return self._password_change_required

    @password_change_required.setter
    def password_change_required(self, password_change_required):
        """Sets the password_change_required of this Request3.

        If `true`, the user will not be able to perform any actions until they change their password.   # noqa: E501

        :param password_change_required: The password_change_required of this Request3.  # noqa: E501
        :type: bool
        """

        self._password_change_required = password_change_required

    @property
    def name(self):
        """Gets the name of this Request3.  # noqa: E501

        A display name for the user.   # noqa: E501

        :return: The name of this Request3.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Request3.

        A display name for the user.   # noqa: E501

        :param name: The name of this Request3.  # noqa: E501
        :type: str
        """
        if name is not None and len(name) > 128:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `128`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this Request3.  # noqa: E501

        A description for the user.   # noqa: E501

        :return: The description of this Request3.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Request3.

        A description for the user.   # noqa: E501

        :param description: The description of this Request3.  # noqa: E501
        :type: str
        """
        if description is not None and len(description) > 2048:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `2048`")  # noqa: E501

        self._description = description

    @property
    def role(self):
        """Gets the role of this Request3.  # noqa: E501

        The user's role ID.   # noqa: E501

        :return: The role of this Request3.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this Request3.

        The user's role ID.   # noqa: E501

        :param role: The role of this Request3.  # noqa: E501
        :type: str
        """

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Request3):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
